// User entity from backend
export interface User {
  id: string;           // UUID generated by backend
  email: string;        // User's email address (unique identifier)
  createdAt: string;    // ISO 8601 timestamp of account creation
}

// Auth state in frontend application
export interface AuthState {
  user: User | null;         // Current authenticated user (null if logged out)
  token: string | null;      // JWT token string (null if logged out)
  isAuthenticated: boolean;  // Derived flag (true if token exists and valid)
  isLoading: boolean;        // Auth initialization/verification in progress
}

// Form input types
export interface LoginCredentials {
  email: string;       // User's email address
  password: string;    // User's password (min 8 characters)
}

export interface SignupCredentials {
  email: string;          // User's email address
  password: string;       // User's password (min 8 characters)
  confirmPassword: string; // Password confirmation (must match password)
}

// Auth API response
export interface AuthResponse {
  user: User;
  token: string;
}
