// Task entity from backend
export interface Task {
  id: string;           // UUID generated by backend
  title: string;        // Task description (1-255 characters)
  completed: boolean;   // Completion status (true = completed, false = incomplete)
  userId: string;       // Owner's user ID (foreign key reference)
  createdAt: string;    // ISO 8601 timestamp of task creation
  updatedAt: string;    // ISO 8601 timestamp of last modification
}

// Form input types for tasks
export interface CreateTaskInput {
  title: string;  // Task title (1-255 characters, trimmed)
}

export interface UpdateTaskInput {
  title: string;  // Updated task title (1-255 characters, trimmed)
}

// Task API responses
export interface TaskListResponse {
  tasks: Task[];
}

export interface TaskResponse {
  task: Task;
}
